# -*- coding: utf-8 -*-
"""background_subtraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ry2BXebu9OCUD8r8ZwjiTddgRx-KMB2
"""

import cv2
from google.colab.patches import cv2_imshow # Import the cv2_imshow function


cap = cv2.VideoCapture('/content/SampleVideo_1280x720_1mb.mp4')
fgbg = cv2.createBackgroundSubtractorMOG2()
'''cv2.createBackgroundSubtractorMOG2() creates a background subtraction model using the MOG2 (Mixture of Gaussians) algorithm.
This algorithm is useful for separating the foreground from the background by modeling the background and detecting moving objects (foreground).'''

while cap.isOpened():
    ret, frame = cap.read()
    if not ret: break

    '''cap.isOpened() checks whether the video file has been successfully opened.
        Inside the while loop, cap.read() reads the next frame of the video.
        ret is a boolean that tells whether the frame was successfully read (True if it was successful, False if it's the end of the video).
        If ret is False (meaning no more frames are available), the loop breaks.'''

    fgmask = fgbg.apply(frame)

    '''fgbg.apply(frame) applies the background subtractor to the current frame (frame).
        The result is a "foreground mask" (fgmask), where the foreground (moving objects) is highlighted, and the background is mostly black.'''

    cv2_imshow(fgmask) # Use cv2_imshow instead of cv2.imshow

    '''cv2_imshow(fgmask) shows the foreground mask (fgmask) in a window within the Colab output.
        This function is a Colab-specific alternative to cv2.imshow that avoids Jupyter kernel crashes.'''



    '''cv2.waitKey(30) waits for 30 milliseconds for a key press. If a key is pressed, it returns the ASCII code of that key.
    & 0xFF ensures we capture the correct key code.
    ord('q') gives the ASCII code for the character 'q'. If the 'q' key is pressed, the loop breaks and the program stops.'''

cap.release()
#cap.release() releases the video capture object, ensuring that resources are freed up.

